export const loanSchemes = [
    {
        id: 1,
        title: "Personal Loan",
        maxAmount: 500000,
        tenure: "6 - 36 months",
        baseRate: 14.0,
        processingFee: "1% + GST",
        description: "For personal needs, medical, travel, or any emergency.",
        tag: "Flexible",
    },
    {
        id: 2,
        title: "Salary Advance",
        maxAmount: 100000,
        tenure: "3 - 12 months",
        baseRate: 8.0,
        processingFee: "Nil",
        description: "Quick cash advance against your salary. Instant disbursement.",
        tag: "Instant",
    },
    {
        id: 3,
        title: "Business Boost Loan",
        maxAmount: 125000,
        tenure: "12 - 48 months",
        baseRate: 13.5,
        processingFee: "1.5% + GST",
        description: "Grow your small business or self-employment venture.",
        tag: "Business",
    },
    {
        id: 4,
        title: "Education Loan",
        maxAmount: 50000,
        tenure: "12 - 60 months",
        baseRate: 11.5,
        processingFee: "1% + GST",
        description: "Fund higher education with flexible repayment.",
        tag: "Low Interest",
    },
    {
        id: 5,
        title: "Two-Wheeler Loan",
        maxAmount: 150000,
        tenure: "12 - 36 months",
        baseRate: 9.5,
        processingFee: "1% + GST",
        description: "Buy your dream bike with low interest and easy EMIs.",
        tag: "Automotive",
    },
    {
        id: 6,
        title: "Medical Emergency Loan",
        maxAmount: 75000,
        tenure: "6 - 24 months",
        baseRate: 10.0,
        processingFee: "0.5% + GST",
        description: "Immediate funds for unplanned medical treatments.",
        tag: "Urgent",
    },
];
